# -*- coding: utf-8 -*-
"""Week-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXy6xMDE43-dTxtFpPhA_xJpasJnPrgV
"""

from sklearn.model_selection import train_test_split

# Split the dataset into Training, Validation, and Testing sets
# Overall ratio: 70% Train, 15% Validation, 15% Test

# Step 1: Split into Train (70%) and Temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(
    df_resampled.drop(columns=['Attack Type']),   # Features
    df_resampled['Attack Type'],                  # Target
    test_size=0.3,
    random_state=42
)

# Step 2: Split the Temporary set equally into Validation and Test (15% each)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,   # 50% of temp = 15% of original
    random_state=42
)

# Print the shapes of all splits
print("Training Set   :", X_train.shape, y_train.shape)
print("Validation Set :", X_val.shape, y_val.shape)
print("Testing Set    :", X_test.shape, y_test.shape)